# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: personnel_financial_advisor_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f ./requirements/requirements.txt ]; then pip install -r ./requirements/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Train the model
      run: |
        python ./model/train.py
    
    - name: Configure Git
      run: |
        git config --global user.email "paavan.sundar@gmail.com"
        git config --global user.name "paavansundar"
        
    - name: Test with pytest
      run: |
        pytest
        
    - name: Log into registry 
      uses: docker/login-action@v2.1.0
      with:
          #registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_UID }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
    
    
    - name: Build and push Docker image
      run: |
        #docker build . --file Dockerfile --tag bike-share-image:$(date +%s)
        docker build . --file Dockerfile --tag personnel_financial_advisor:latest
        docker tag personnel_financial_advisor:latest paavansundar/personnel_financial_advisor:latest
        docker push paavansundar/personnel_financial_advisor:latest
        
    - name: Docker logout
      run: docker logout
        
